### ISSUE TITLE
Add css for custom scrollbar

### ISSUE THREAD

**Issue by Rishabh-malhotraa** [bchiang7/v4#131]
WE can think of adding CSS for a custom scrollbar like the following in the `index.css` file.

Currently, we get a white scrollbar(on windows) it would be better if I get a dark themed scrollbar when I open the website

| Before | After |
|----|-----|
|![image](https://user-images.githubusercontent.com/54576074/114454398-33e87880-9bf8-11eb-9fb2-d3efbe797d58.png)|![image](https://user-images.githubusercontent.com/54576074/114455148-07812c00-9bf9-11eb-83ec-a182ae7e52f1.png)|

``` css
  /* width */
::-webkit-scrollbar {
  width: 10px;
}

/* Track */
::-webkit-scrollbar-track {
  background: #232728;
  /* background: #3e3e42; */
}

/* Handle */
::-webkit-scrollbar-thumb {
  background: #888;
  background: #555;
}

/* Handle on hover */
::-webkit-scrollbar-thumb:hover {
  background: #464c4f;
}

```
