### ISSUE TITLE
[Feature] - Auto Deployment of Your Fork/Website 

### ISSUE THREAD

**Issue by adithyaakrishna** [bchiang7/v4#211]
Hi All 👋🏻 
I am a huge fan of this portfolio website and have been using it for like an year and half. One issue for me was that I had to clone, make changes and run `npm run deploy` [Deploy Script](https://github.com/adithyaakrishna/adithyaakrishna.github.io/blob/source/package.json#L18) the site to deploy on GitHub Pages which would take quite some time and I was not able to make changes on the go be it through GitHub UI (Both PC & Mobile). So I wanted a GitHub Action to run whenever I make some changes and commit it to a specific branch using the GitHub UI itself. Hence I kind-of wrote a workflow for this,

```yaml
name: Deploy Website 🕸
on:
  push:
    branches:
      - source # Change the branch name to your main one in which source code is there 
jobs:
  Build-N-Deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn
          npm run deploy
```

**Note**: For this to run, you need the `npm run deploy` configured

Hope this helps someone 🚀 

PS. Thanks @bchiang7 for this amazing portfolio :)
